"""empty message

Revision ID: 258cfba17bcd
Revises: e71b6716d4a9
Create Date: 2019-10-18 20:46:21.332835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258cfba17bcd'
down_revision = 'e71b6716d4a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
